import { Space_Mono } from "next/font/google";
import { Work_Sans } from 'next/font/google';
import { Nabvar , Footer} from "@/components";

import '@/app/globals.css'

const workSans = Work_Sans({
  variable:"--font-work-sans",
  subsets: ['latin'],
  weight: ['400', '600', '700'], 
  display: 'swap',
});
const spaceMono = Space_Mono({
  variable: "--font-space-mono", 
  subsets: ["latin"],
  weight: ["400", "700"], 
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
            <html lang="en"  className="h-full">
              <body
                className={`${workSans.variable} ${spaceMono.variable} flex flex-col h-full`} 
              >
                <Nabvar/>
                <div className="flex-1 flex">
                    {children}
                </div>
                <Footer/>
              </body>
            </html>
  );
}
